version: '3.8'

services:
  paymentapi:
    image: jokoyoski/paymentapi:v2
    ports:
      - "5293:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql5073.site4now.net;Database=db_a7d48d_paymentapi;User Id=db_a7d48d_paymentapi_admin;Password=Jokoyoski200@;MultipleActiveResultSets=true;
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_ENVIRONMENT=Development
      - AllowedHosts=*
